[raspberry-gpio]
enabled = false
bcm5 = play_pause,active_low,100
bcm6 = volume_down,active_low,100
bcm16 = next,active_low,100
bcm20 = volume_up,active_low,100
bcm24 = volume_up,active_low,100

[file]
enabled = true
media_dirs = ~/Music
show_dotfiles = false
excluded_file_extensions =
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .pdf
  .png
  .txt
  .zip
follow_symlinks = false
metadata_timeout = 1000

[local]
media_dir = ~/Music
scan_timeout = 5000

# [pidi]
# commented out until mopidy-pidi/pidi-display-st7789 are added back to pyproject.toml
# enabled = true
# display = st7789
# rotated an additional 180 degrees to be more ergonomic
# rotation = 270

[mpd]
hostname = 0.0.0.0
port = 6600

[http]
hostname = 0.0.0.0
port = 6680

[audio]
mixer_volume = 40
output = alsasink device=hw:1,0
