minimum_prek_version = "0.4.11"
default_install_hook_types = ["pre-commit", "pre-push", "commit-msg"]
fail_fast = true


# Commit message specific checks
[[repos]]
repo = "https://github.com/compilerla/conventional-pre-commit"
rev = "v4.4.0"
[[repos.hooks]]
id = "conventional-pre-commit"
stages = ["commit-msg"]

[[repos]]
repo = "https://github.com/crate-ci/typos"
rev = "v1.50.0"


[[repos.hooks]]
id = "typos"
name = "Spell check commit message"
args = ["--force-exclude"]
stages = ["commit-msg"]

# Run python checks first as it handles a lot of the
# steps done by other stages
[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.16.5"

[[repos.hooks]]
id = "ruff-format"

[[repos.hooks]]
id = "ruff"
args = ["--fix"]


[[repos]]
repo = "https://github.com/pre-commit/mirrors-mypy"
rev = "v2.3.1"

[[repos.hooks]]
id = "mypy"
args = ["--ignore-missing-imports"]
additional_dependencies = ["types-requests"]

# Basic checks (while ignoring python)
[[repos]]
repo = "builtin"

[[repos.hooks]]
id = "trailing-whitespace"
exclude_types = ["python"]

[[repos.hooks]]
id = "mixed-line-ending"
args = ["--fix=lf"]
exclude_types = ["python"]

[[repos.hooks]]
id = "check-merge-conflict"

[[repos.hooks]]
id = "check-added-large-files"
args = ["--maxkb=1000"]

# Deeper checks that take more time
[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"

[[repos.hooks]]
id = "debug-statements"

# Format non python files. This is done after so that python
# related issues are prioritized as they are they are used the
# most so failing fast on them first saves time
[[repos]]
repo = "builtin"

[[repos.hooks]]
id = "check-yaml"

[[repos.hooks]]
id = "check-toml"

[[repos.hooks]]
id = "check-json"

[[repos]]
repo = "https://github.com/pre-commit/mirrors-prettier"
rev = "v4.0.0-alpha.8"

[[repos.hooks]]
id = "prettier"
types_or = ["toml", "yaml"]

[[repos]]
repo = "https://github.com/igorshubovych/markdownlint-cli"
rev = "v0.49.1"

[[repos.hooks]]
id = "markdownlint-fix"
args = ["--disable", "MD013"]


# ---------------------------------------------------------
# 5. SPELL CHECKING (Pre-commit)
# ---------------------------------------------------------
[[repos]]
repo = "https://github.com/crate-ci/typos"
rev = "v1.50.0"

[[repos.hooks]]
id = "typos"
name = "Spell check commit contents"
args = ["--force-exclude"]
stages = ["pre-commit"]
